// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        mavenCentral()
        google()
        maven { url 'https://plugins.gradle.org/m2' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.2'

        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.4.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral()
        google()
        maven { url 'https://plugins.gradle.org/m2' }
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        if (perferUseLocalMaven.toBoolean() || isModuleAsApp.toBoolean()) {
            final localMavenRepository = rootProject.file("../../../MavenRepository")
            if (localMavenRepository.exists()) {
                maven { url localMavenRepository.toURI() }
            } else {
                throw new IllegalStateException("Please clone https://github.com/TranscodeGroup/MavenRepository.git into the dir: $localMavenRepository")
            }
        }
    }
}

ext {
    compileSdkVersion = 30
    buildToolsVersion = "30.0.3"

    targetSdkVersion = 30

    versionCode = 800800
    versionName = "0.8.8"

    ijkplayerLib = { name, forceUseLocalMaven = false ->
        (perferUseLocalMaven.toBoolean() || forceUseLocalMaven)
                ? "cn.transcodegroup.ijkplayer:$name:$VERSION_NAME.$LOCALE_MAVEN_VERSION_SUFFIX"
                : project(":$name")
    }
}

wrapper {
    gradleVersion = '5.6.4'
}
