apply plugin: 'maven-publish'

// Perform `publishReleasePublicationToLocalRepository` to publish aar to `MavenRepository` folder
// @see https://gist.github.com/Robyer/a6578e60127418b380ca133a1291f017
group = 'cn.transcodegroup.ijkplayer'
version = "$VERSION_NAME.$VERSION_SUFFIX"

task androidJavadocs(type: Javadoc) {
    failOnError false
    source = android.sourceSets.main.java.srcDirs
    classpath += project.files(android.getBootClasspath().join(File.pathSeparator))
    android.libraryVariants.all { variant ->
        if (variant.name == 'release') {
            owner.classpath += variant.javaCompileProvider.get().classpath
        }
    }
    exclude '**/R.html', '**/R.*.html', '**/index.html'
}

task androidJavadocsJar(type: Jar, dependsOn: androidJavadocs) {
    archiveClassifier.set('javadoc')
    from androidJavadocs.destinationDir
}

task androidSourcesJar(type: Jar) {
    archiveClassifier.set('sources')
    from android.sourceSets.main.java.srcDirs
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release

                artifact androidJavadocsJar
                artifact androidSourcesJar
            }
        }
        repositories {
            maven {
                name = 'local'
                url = rootProject.file("../../../MavenRepository").toURI()
            }
        }
    }
}
